version: '3.8'

services:
  web:
    build:
      context: .
    user: "${UID}:${GID}"
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --lifespan on"
    volumes:
      - ./tg-scraping/telethon_fastapi/:/app
      - ./tg-scraping/telethon_fastapi/saved_session/:/app/saved_session/
    env_file:
      - ./.env
    ports:
      - 9009:8000
